import React from "react";
import { Link } from "react-router-dom";
import { Button } from "../components/ui/button";
import { Card, CardContent } from "../components/ui/card";
import {
  Sparkles,
  Brain,
  TrendingUp,
  Users,
  ArrowRight,
  CheckCircle,
} from "lucide-react";

const Home = () => {
  const features = [
    {
      icon: <Brain className="h-8 w-8 text-blue-500" />,
      title: "AI-Powered Mnemonics",
      description:
        "Memorable stories and visual associations generated by AI to help you remember kanji effortlessly",
    },
    {
      icon: <TrendingUp className="h-8 w-8 text-green-500" />,
      title: "Spaced Repetition",
      description:
        "Scientifically proven SRS algorithm ensures you review at the perfect time for long-term retention",
    },
    {
      icon: <Sparkles className="h-8 w-8 text-purple-500" />,
      title: "Visual Learning",
      description:
        "AI-generated illustrations bring kanji to life with vivid, unforgettable imagery",
    },
    {
      icon: <Users className="h-8 w-8 text-orange-500" />,
      title: "Adaptive Learning",
      description:
        "Personalized lessons that adapt to your learning style and pace",
    },
  ];

  const stats = [
    { number: "2,136", label: "Kanji" },
    { number: "6,000+", label: "Vocabulary" },
    { number: "60", label: "Levels" },
    { number: "∞", label: "Mnemonics" },
  ];

  return (
    <div className="space-y-16">
      {/* Hero Section */}
      <section className="text-center py-16">
        <h1 className="text-5xl md:text-6xl font-bold mb-6">
          <span className="bg-gradient-to-r from-blue-600 to-purple-600 bg-clip-text text-transparent">
            Master Kanji
          </span>
          <br />
          <span className="text-gray-800 dark:text-white">
            with AI & Mnemonics
          </span>
        </h1>
        <p className="text-xl text-muted-foreground max-w-2xl mx-auto mb-8">
          Learn 2,000+ kanji through unforgettable stories, vivid imagery, and
          an AI tutor that adapts to your learning style
        </p>
        <div className="flex gap-4 justify-center">
          <Link to="/register">
            <Button size="lg" className="gap-2">
              Start Learning Free
              <ArrowRight className="h-4 w-4" />
            </Button>
          </Link>
          <Link to="/kanji">
            <Button size="lg" variant="outline">
              Browse Kanji
            </Button>
          </Link>
        </div>
      </section>

      {/* Stats Section */}
      <section className="py-8">
        <div className="grid grid-cols-2 md:grid-cols-4 gap-8">
          {stats.map((stat, index) => (
            <div key={index} className="text-center">
              <div className="text-3xl md:text-4xl font-bold text-primary">
                {stat.number}
              </div>
              <div className="text-muted-foreground">{stat.label}</div>
            </div>
          ))}
        </div>
      </section>

      {/* Features Section */}
      <section className="py-8">
        <h2 className="text-3xl font-bold text-center mb-12">
          Why KanjAI Works
        </h2>
        <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-6">
          {features.map((feature, index) => (
            <Card key={index} className="hover:shadow-lg transition-shadow">
              <CardContent className="p-6">
                <div className="mb-4">{feature.icon}</div>
                <h3 className="font-semibold text-lg mb-2">{feature.title}</h3>
                <p className="text-sm text-muted-foreground">
                  {feature.description}
                </p>
              </CardContent>
            </Card>
          ))}
        </div>
      </section>

      {/* Example Section */}
      <section className="py-8">
        <Card className="max-w-4xl mx-auto">
          <CardContent className="p-8">
            <h2 className="text-2xl font-bold mb-6 text-center">
              See How It Works
            </h2>
            <div className="grid md:grid-cols-2 gap-8">
              <div>
                <div className="text-8xl font-bold text-center mb-4 kanji-display">
                  火
                </div>
                <div className="text-center text-xl mb-2">Fire</div>
                <div className="text-center text-muted-foreground">ka, hi</div>
              </div>
              <div className="space-y-4">
                <div>
                  <h3 className="font-semibold mb-2 flex items-center gap-2">
                    <CheckCircle className="h-5 w-5 text-green-500" />
                    Visual Mnemonic
                  </h3>
                  <p className="text-sm text-muted-foreground">
                    "See the three flames dancing on top? And those logs burning
                    below? But wait - it looks like the person radical... OH NO,
                    THEY'RE ON FIRE!"
                  </p>
                </div>
                <div>
                  <h3 className="font-semibold mb-2 flex items-center gap-2">
                    <CheckCircle className="h-5 w-5 text-green-500" />
                    Reading Memory Hook
                  </h3>
                  <p className="text-sm text-muted-foreground">
                    "Your CAR (か) is on fire! Feel the HEAT (ひ) radiating from
                    it!"
                  </p>
                </div>
              </div>
            </div>
          </CardContent>
        </Card>
      </section>

      {/* CTA Section */}
      <section className="text-center py-16">
        <h2 className="text-3xl font-bold mb-4">Ready to Master Japanese?</h2>
        <p className="text-xl text-muted-foreground mb-8">
          Join thousands learning kanji the unforgettable way
        </p>
        <Link to="/register">
          <Button size="lg" className="gap-2">
            Start Your Journey
            <ArrowRight className="h-4 w-4" />
          </Button>
        </Link>
      </section>
    </div>
  );
};

export default Home;
